// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZAn1ovK4o6Q1hN2uRbM6dVgNu5oMA8Y8',
    appId: '1:260529636257:web:3bf632d9b480f1909401e0',
    messagingSenderId: '260529636257',
    projectId: 'bookswap-8f9a1',
    authDomain: 'bookswap-8f9a1.firebaseapp.com',
    storageBucket: 'bookswap-8f9a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfD4JPT7WStFdNYdkAd59CRptd5WjsNGI',
    appId: '1:260529636257:android:6424d97bd642eeac9401e0',
    messagingSenderId: '260529636257',
    projectId: 'bookswap-8f9a1',
    storageBucket: 'bookswap-8f9a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOxWAAvEMVYfaO-_T3icf9TE-iyGmeMv4',
    appId: '1:260529636257:ios:286fafc71cfb00d89401e0',
    messagingSenderId: '260529636257',
    projectId: 'bookswap-8f9a1',
    storageBucket: 'bookswap-8f9a1.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOxWAAvEMVYfaO-_T3icf9TE-iyGmeMv4',
    appId: '1:260529636257:ios:286fafc71cfb00d89401e0',
    messagingSenderId: '260529636257',
    projectId: 'bookswap-8f9a1',
    storageBucket: 'bookswap-8f9a1.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZAn1ovK4o6Q1hN2uRbM6dVgNu5oMA8Y8',
    appId: '1:260529636257:web:fc67f22b941930459401e0',
    messagingSenderId: '260529636257',
    projectId: 'bookswap-8f9a1',
    authDomain: 'bookswap-8f9a1.firebaseapp.com',
    storageBucket: 'bookswap-8f9a1.firebasestorage.app',
  );
}
